# Generated by Django 5.0.7 on 2024-07-18 21:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('readtime', models.IntegerField(default=2)),
                ('date', models.DateField()),
                ('coverimage', models.ImageField(upload_to='blog_covers')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
