# Generated by Django 5.0.6 on 2024-06-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_readtime_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='coverimage',
            field=models.ImageField(upload_to='home/blogs/'),
        ),
    ]
