# Generated by Django 5.0.6 on 2024-06-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blog_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='coverimage',
            field=models.ImageField(upload_to='blog_covers'),
        ),
    ]
